spring.application.name=rabbitmq-producer

spring.rabbitmq.queue.name=queue
spring.rabbitmq.json.queue.name=Jsonqueue
spring.rabbitmq.exchange.name=root
spring.rabbitmq.bindingKey.name=key
spring.rabbitmq.json.bindingKey.name=jsonKey


# logging.level.org.springframework=DEBUG

